// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: battle.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 放置防御塔请求
type PlaceTowerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TowerType     int32                  `protobuf:"varint,1,opt,name=tower_type,json=towerType,proto3" json:"tower_type,omitempty"`
	Position      *Vector3               `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceTowerRequest) Reset() {
	*x = PlaceTowerRequest{}
	mi := &file_battle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceTowerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceTowerRequest) ProtoMessage() {}

func (x *PlaceTowerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceTowerRequest.ProtoReflect.Descriptor instead.
func (*PlaceTowerRequest) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{0}
}

func (x *PlaceTowerRequest) GetTowerType() int32 {
	if x != nil {
		return x.TowerType
	}
	return 0
}

func (x *PlaceTowerRequest) GetPosition() *Vector3 {
	if x != nil {
		return x.Position
	}
	return nil
}

// 放置防御塔响应
type PlaceTowerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TowerId       string                 `protobuf:"bytes,2,opt,name=tower_id,json=towerId,proto3" json:"tower_id,omitempty"`
	TowerType     int32                  `protobuf:"varint,3,opt,name=tower_type,json=towerType,proto3" json:"tower_type,omitempty"`
	Position      *Vector3               `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	Gold          int32                  `protobuf:"varint,5,opt,name=gold,proto3" json:"gold,omitempty"` // 剩余金币
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceTowerResponse) Reset() {
	*x = PlaceTowerResponse{}
	mi := &file_battle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceTowerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceTowerResponse) ProtoMessage() {}

func (x *PlaceTowerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceTowerResponse.ProtoReflect.Descriptor instead.
func (*PlaceTowerResponse) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{1}
}

func (x *PlaceTowerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PlaceTowerResponse) GetTowerId() string {
	if x != nil {
		return x.TowerId
	}
	return ""
}

func (x *PlaceTowerResponse) GetTowerType() int32 {
	if x != nil {
		return x.TowerType
	}
	return 0
}

func (x *PlaceTowerResponse) GetPosition() *Vector3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *PlaceTowerResponse) GetGold() int32 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *PlaceTowerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 升级防御塔请求
type UpgradeTowerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TowerId       string                 `protobuf:"bytes,1,opt,name=tower_id,json=towerId,proto3" json:"tower_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeTowerRequest) Reset() {
	*x = UpgradeTowerRequest{}
	mi := &file_battle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeTowerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeTowerRequest) ProtoMessage() {}

func (x *UpgradeTowerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeTowerRequest.ProtoReflect.Descriptor instead.
func (*UpgradeTowerRequest) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{2}
}

func (x *UpgradeTowerRequest) GetTowerId() string {
	if x != nil {
		return x.TowerId
	}
	return ""
}

// 升级防御塔响应
type UpgradeTowerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TowerId       string                 `protobuf:"bytes,2,opt,name=tower_id,json=towerId,proto3" json:"tower_id,omitempty"`
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Cost          int32                  `protobuf:"varint,4,opt,name=cost,proto3" json:"cost,omitempty"` // 升级花费
	Gold          int32                  `protobuf:"varint,5,opt,name=gold,proto3" json:"gold,omitempty"` // 剩余金币
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeTowerResponse) Reset() {
	*x = UpgradeTowerResponse{}
	mi := &file_battle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeTowerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeTowerResponse) ProtoMessage() {}

func (x *UpgradeTowerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeTowerResponse.ProtoReflect.Descriptor instead.
func (*UpgradeTowerResponse) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{3}
}

func (x *UpgradeTowerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpgradeTowerResponse) GetTowerId() string {
	if x != nil {
		return x.TowerId
	}
	return ""
}

func (x *UpgradeTowerResponse) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UpgradeTowerResponse) GetCost() int32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *UpgradeTowerResponse) GetGold() int32 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *UpgradeTowerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 出售防御塔请求
type SellTowerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TowerId       string                 `protobuf:"bytes,1,opt,name=tower_id,json=towerId,proto3" json:"tower_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellTowerRequest) Reset() {
	*x = SellTowerRequest{}
	mi := &file_battle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellTowerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellTowerRequest) ProtoMessage() {}

func (x *SellTowerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellTowerRequest.ProtoReflect.Descriptor instead.
func (*SellTowerRequest) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{4}
}

func (x *SellTowerRequest) GetTowerId() string {
	if x != nil {
		return x.TowerId
	}
	return ""
}

// 出售防御塔响应
type SellTowerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TowerId       string                 `protobuf:"bytes,2,opt,name=tower_id,json=towerId,proto3" json:"tower_id,omitempty"`
	Refund        int32                  `protobuf:"varint,3,opt,name=refund,proto3" json:"refund,omitempty"` // 返还金币
	Gold          int32                  `protobuf:"varint,4,opt,name=gold,proto3" json:"gold,omitempty"`     // 剩余金币
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellTowerResponse) Reset() {
	*x = SellTowerResponse{}
	mi := &file_battle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellTowerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellTowerResponse) ProtoMessage() {}

func (x *SellTowerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellTowerResponse.ProtoReflect.Descriptor instead.
func (*SellTowerResponse) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{5}
}

func (x *SellTowerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SellTowerResponse) GetTowerId() string {
	if x != nil {
		return x.TowerId
	}
	return ""
}

func (x *SellTowerResponse) GetRefund() int32 {
	if x != nil {
		return x.Refund
	}
	return 0
}

func (x *SellTowerResponse) GetGold() int32 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *SellTowerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 使用技能请求
type UseSkillRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SkillId        int32                  `protobuf:"varint,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	TargetPosition *Vector3               `protobuf:"bytes,2,opt,name=target_position,json=targetPosition,proto3" json:"target_position,omitempty"`
	TargetId       string                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // 目标ID（敌人或塔）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UseSkillRequest) Reset() {
	*x = UseSkillRequest{}
	mi := &file_battle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseSkillRequest) ProtoMessage() {}

func (x *UseSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseSkillRequest.ProtoReflect.Descriptor instead.
func (*UseSkillRequest) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{6}
}

func (x *UseSkillRequest) GetSkillId() int32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *UseSkillRequest) GetTargetPosition() *Vector3 {
	if x != nil {
		return x.TargetPosition
	}
	return nil
}

func (x *UseSkillRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

// 使用技能响应
type UseSkillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SkillId       int32                  `protobuf:"varint,2,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseSkillResponse) Reset() {
	*x = UseSkillResponse{}
	mi := &file_battle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseSkillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseSkillResponse) ProtoMessage() {}

func (x *UseSkillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseSkillResponse.ProtoReflect.Descriptor instead.
func (*UseSkillResponse) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{7}
}

func (x *UseSkillResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UseSkillResponse) GetSkillId() int32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *UseSkillResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 波次开始广播
type WaveStartBroadcast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WaveNum       int32                  `protobuf:"varint,1,opt,name=wave_num,json=waveNum,proto3" json:"wave_num,omitempty"`
	EnemyCount    int32                  `protobuf:"varint,2,opt,name=enemy_count,json=enemyCount,proto3" json:"enemy_count,omitempty"`    // 本波敌人数量
	TotalWaves    int32                  `protobuf:"varint,3,opt,name=total_waves,json=totalWaves,proto3" json:"total_waves,omitempty"`    // 总波数
	PrepareTime   int32                  `protobuf:"varint,4,opt,name=prepare_time,json=prepareTime,proto3" json:"prepare_time,omitempty"` // 准备时间(秒)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaveStartBroadcast) Reset() {
	*x = WaveStartBroadcast{}
	mi := &file_battle_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaveStartBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaveStartBroadcast) ProtoMessage() {}

func (x *WaveStartBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaveStartBroadcast.ProtoReflect.Descriptor instead.
func (*WaveStartBroadcast) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{8}
}

func (x *WaveStartBroadcast) GetWaveNum() int32 {
	if x != nil {
		return x.WaveNum
	}
	return 0
}

func (x *WaveStartBroadcast) GetEnemyCount() int32 {
	if x != nil {
		return x.EnemyCount
	}
	return 0
}

func (x *WaveStartBroadcast) GetTotalWaves() int32 {
	if x != nil {
		return x.TotalWaves
	}
	return 0
}

func (x *WaveStartBroadcast) GetPrepareTime() int32 {
	if x != nil {
		return x.PrepareTime
	}
	return 0
}

// 波次完成广播
type WaveCompleteBroadcast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WaveNum       int32                  `protobuf:"varint,1,opt,name=wave_num,json=waveNum,proto3" json:"wave_num,omitempty"`
	Reward        int32                  `protobuf:"varint,2,opt,name=reward,proto3" json:"reward,omitempty"`
	KillCount     int32                  `protobuf:"varint,3,opt,name=kill_count,json=killCount,proto3" json:"kill_count,omitempty"`       // 击杀数
	TotalDamage   int32                  `protobuf:"varint,4,opt,name=total_damage,json=totalDamage,proto3" json:"total_damage,omitempty"` // 总伤害
	IsPerfect     bool                   `protobuf:"varint,5,opt,name=is_perfect,json=isPerfect,proto3" json:"is_perfect,omitempty"`       // 是否完美通关（无漏怪）
	BonusReward   int32                  `protobuf:"varint,6,opt,name=bonus_reward,json=bonusReward,proto3" json:"bonus_reward,omitempty"` // 额外奖励
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaveCompleteBroadcast) Reset() {
	*x = WaveCompleteBroadcast{}
	mi := &file_battle_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaveCompleteBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaveCompleteBroadcast) ProtoMessage() {}

func (x *WaveCompleteBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaveCompleteBroadcast.ProtoReflect.Descriptor instead.
func (*WaveCompleteBroadcast) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{9}
}

func (x *WaveCompleteBroadcast) GetWaveNum() int32 {
	if x != nil {
		return x.WaveNum
	}
	return 0
}

func (x *WaveCompleteBroadcast) GetReward() int32 {
	if x != nil {
		return x.Reward
	}
	return 0
}

func (x *WaveCompleteBroadcast) GetKillCount() int32 {
	if x != nil {
		return x.KillCount
	}
	return 0
}

func (x *WaveCompleteBroadcast) GetTotalDamage() int32 {
	if x != nil {
		return x.TotalDamage
	}
	return 0
}

func (x *WaveCompleteBroadcast) GetIsPerfect() bool {
	if x != nil {
		return x.IsPerfect
	}
	return false
}

func (x *WaveCompleteBroadcast) GetBonusReward() int32 {
	if x != nil {
		return x.BonusReward
	}
	return 0
}

// 游戏结束广播
type GameOverBroadcast struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	IsVictory   bool                   `protobuf:"varint,1,opt,name=is_victory,json=isVictory,proto3" json:"is_victory,omitempty"`
	TotalWaves  int32                  `protobuf:"varint,2,opt,name=total_waves,json=totalWaves,proto3" json:"total_waves,omitempty"`
	KillCount   int32                  `protobuf:"varint,3,opt,name=kill_count,json=killCount,proto3" json:"kill_count,omitempty"`
	TotalDamage int64                  `protobuf:"varint,4,opt,name=total_damage,json=totalDamage,proto3" json:"total_damage,omitempty"`
	Score       int32                  `protobuf:"varint,5,opt,name=score,proto3" json:"score,omitempty"`
	// 各玩家统计
	PlayerStats []*PlayerGameStats `protobuf:"bytes,6,rep,name=player_stats,json=playerStats,proto3" json:"player_stats,omitempty"`
	// 奖励
	Reward        *GameReward `protobuf:"bytes,7,opt,name=reward,proto3" json:"reward,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameOverBroadcast) Reset() {
	*x = GameOverBroadcast{}
	mi := &file_battle_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameOverBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameOverBroadcast) ProtoMessage() {}

func (x *GameOverBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameOverBroadcast.ProtoReflect.Descriptor instead.
func (*GameOverBroadcast) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{10}
}

func (x *GameOverBroadcast) GetIsVictory() bool {
	if x != nil {
		return x.IsVictory
	}
	return false
}

func (x *GameOverBroadcast) GetTotalWaves() int32 {
	if x != nil {
		return x.TotalWaves
	}
	return 0
}

func (x *GameOverBroadcast) GetKillCount() int32 {
	if x != nil {
		return x.KillCount
	}
	return 0
}

func (x *GameOverBroadcast) GetTotalDamage() int64 {
	if x != nil {
		return x.TotalDamage
	}
	return 0
}

func (x *GameOverBroadcast) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *GameOverBroadcast) GetPlayerStats() []*PlayerGameStats {
	if x != nil {
		return x.PlayerStats
	}
	return nil
}

func (x *GameOverBroadcast) GetReward() *GameReward {
	if x != nil {
		return x.Reward
	}
	return nil
}

// 玩家游戏统计
type PlayerGameStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	KillCount     int32                  `protobuf:"varint,3,opt,name=kill_count,json=killCount,proto3" json:"kill_count,omitempty"`
	TotalDamage   int64                  `protobuf:"varint,4,opt,name=total_damage,json=totalDamage,proto3" json:"total_damage,omitempty"`
	TowerCount    int32                  `protobuf:"varint,5,opt,name=tower_count,json=towerCount,proto3" json:"tower_count,omitempty"` // 建造塔数量
	GoldEarned    int32                  `protobuf:"varint,6,opt,name=gold_earned,json=goldEarned,proto3" json:"gold_earned,omitempty"` // 获得金币
	GoldSpent     int32                  `protobuf:"varint,7,opt,name=gold_spent,json=goldSpent,proto3" json:"gold_spent,omitempty"`    // 花费金币
	Score         int32                  `protobuf:"varint,8,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerGameStats) Reset() {
	*x = PlayerGameStats{}
	mi := &file_battle_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerGameStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerGameStats) ProtoMessage() {}

func (x *PlayerGameStats) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerGameStats.ProtoReflect.Descriptor instead.
func (*PlayerGameStats) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{11}
}

func (x *PlayerGameStats) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerGameStats) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *PlayerGameStats) GetKillCount() int32 {
	if x != nil {
		return x.KillCount
	}
	return 0
}

func (x *PlayerGameStats) GetTotalDamage() int64 {
	if x != nil {
		return x.TotalDamage
	}
	return 0
}

func (x *PlayerGameStats) GetTowerCount() int32 {
	if x != nil {
		return x.TowerCount
	}
	return 0
}

func (x *PlayerGameStats) GetGoldEarned() int32 {
	if x != nil {
		return x.GoldEarned
	}
	return 0
}

func (x *PlayerGameStats) GetGoldSpent() int32 {
	if x != nil {
		return x.GoldSpent
	}
	return 0
}

func (x *PlayerGameStats) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

// 游戏奖励
type GameReward struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coin          int32                  `protobuf:"varint,1,opt,name=coin,proto3" json:"coin,omitempty"`  // 游戏币
	Exp           int32                  `protobuf:"varint,2,opt,name=exp,proto3" json:"exp,omitempty"`    // 经验
	Items         []*ItemReward          `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"` // 道具奖励
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameReward) Reset() {
	*x = GameReward{}
	mi := &file_battle_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameReward) ProtoMessage() {}

func (x *GameReward) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameReward.ProtoReflect.Descriptor instead.
func (*GameReward) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{12}
}

func (x *GameReward) GetCoin() int32 {
	if x != nil {
		return x.Coin
	}
	return 0
}

func (x *GameReward) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *GameReward) GetItems() []*ItemReward {
	if x != nil {
		return x.Items
	}
	return nil
}

// 道具奖励
type ItemReward struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int32                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemCount     int32                  `protobuf:"varint,2,opt,name=item_count,json=itemCount,proto3" json:"item_count,omitempty"`
	ItemName      string                 `protobuf:"bytes,3,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemReward) Reset() {
	*x = ItemReward{}
	mi := &file_battle_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemReward) ProtoMessage() {}

func (x *ItemReward) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemReward.ProtoReflect.Descriptor instead.
func (*ItemReward) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{13}
}

func (x *ItemReward) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ItemReward) GetItemCount() int32 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

func (x *ItemReward) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

// 暂停游戏请求
type PauseGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsPause       bool                   `protobuf:"varint,1,opt,name=is_pause,json=isPause,proto3" json:"is_pause,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseGameRequest) Reset() {
	*x = PauseGameRequest{}
	mi := &file_battle_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseGameRequest) ProtoMessage() {}

func (x *PauseGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseGameRequest.ProtoReflect.Descriptor instead.
func (*PauseGameRequest) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{14}
}

func (x *PauseGameRequest) GetIsPause() bool {
	if x != nil {
		return x.IsPause
	}
	return false
}

// 暂停游戏响应
type PauseGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	IsPause       bool                   `protobuf:"varint,2,opt,name=is_pause,json=isPause,proto3" json:"is_pause,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseGameResponse) Reset() {
	*x = PauseGameResponse{}
	mi := &file_battle_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseGameResponse) ProtoMessage() {}

func (x *PauseGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseGameResponse.ProtoReflect.Descriptor instead.
func (*PauseGameResponse) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{15}
}

func (x *PauseGameResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PauseGameResponse) GetIsPause() bool {
	if x != nil {
		return x.IsPause
	}
	return false
}

func (x *PauseGameResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_battle_proto protoreflect.FileDescriptor

const file_battle_proto_rawDesc = "" +
	"\n" +
	"\fbattle.proto\x12\ftowerdefense\x1a\fcommon.proto\"X\n" +
	"\x11PlaceTowerRequest\x12\x1d\n" +
	"\n" +
	"tower_type\x18\x01 \x01(\x05R\ttowerType\x12$\n" +
	"\bposition\x18\x02 \x01(\v2\b.Vector3R\bposition\"\xbc\x01\n" +
	"\x12PlaceTowerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\btower_id\x18\x02 \x01(\tR\atowerId\x12\x1d\n" +
	"\n" +
	"tower_type\x18\x03 \x01(\x05R\ttowerType\x12$\n" +
	"\bposition\x18\x04 \x01(\v2\b.Vector3R\bposition\x12\x12\n" +
	"\x04gold\x18\x05 \x01(\x05R\x04gold\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\"0\n" +
	"\x13UpgradeTowerRequest\x12\x19\n" +
	"\btower_id\x18\x01 \x01(\tR\atowerId\"\xa3\x01\n" +
	"\x14UpgradeTowerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\btower_id\x18\x02 \x01(\tR\atowerId\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x12\n" +
	"\x04cost\x18\x04 \x01(\x05R\x04cost\x12\x12\n" +
	"\x04gold\x18\x05 \x01(\x05R\x04gold\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\"-\n" +
	"\x10SellTowerRequest\x12\x19\n" +
	"\btower_id\x18\x01 \x01(\tR\atowerId\"\x8e\x01\n" +
	"\x11SellTowerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\btower_id\x18\x02 \x01(\tR\atowerId\x12\x16\n" +
	"\x06refund\x18\x03 \x01(\x05R\x06refund\x12\x12\n" +
	"\x04gold\x18\x04 \x01(\x05R\x04gold\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"|\n" +
	"\x0fUseSkillRequest\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\x05R\askillId\x121\n" +
	"\x0ftarget_position\x18\x02 \x01(\v2\b.Vector3R\x0etargetPosition\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\"a\n" +
	"\x10UseSkillResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\bskill_id\x18\x02 \x01(\x05R\askillId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x94\x01\n" +
	"\x12WaveStartBroadcast\x12\x19\n" +
	"\bwave_num\x18\x01 \x01(\x05R\awaveNum\x12\x1f\n" +
	"\venemy_count\x18\x02 \x01(\x05R\n" +
	"enemyCount\x12\x1f\n" +
	"\vtotal_waves\x18\x03 \x01(\x05R\n" +
	"totalWaves\x12!\n" +
	"\fprepare_time\x18\x04 \x01(\x05R\vprepareTime\"\xce\x01\n" +
	"\x15WaveCompleteBroadcast\x12\x19\n" +
	"\bwave_num\x18\x01 \x01(\x05R\awaveNum\x12\x16\n" +
	"\x06reward\x18\x02 \x01(\x05R\x06reward\x12\x1d\n" +
	"\n" +
	"kill_count\x18\x03 \x01(\x05R\tkillCount\x12!\n" +
	"\ftotal_damage\x18\x04 \x01(\x05R\vtotalDamage\x12\x1d\n" +
	"\n" +
	"is_perfect\x18\x05 \x01(\bR\tisPerfect\x12!\n" +
	"\fbonus_reward\x18\x06 \x01(\x05R\vbonusReward\"\x9f\x02\n" +
	"\x11GameOverBroadcast\x12\x1d\n" +
	"\n" +
	"is_victory\x18\x01 \x01(\bR\tisVictory\x12\x1f\n" +
	"\vtotal_waves\x18\x02 \x01(\x05R\n" +
	"totalWaves\x12\x1d\n" +
	"\n" +
	"kill_count\x18\x03 \x01(\x05R\tkillCount\x12!\n" +
	"\ftotal_damage\x18\x04 \x01(\x03R\vtotalDamage\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x05R\x05score\x12@\n" +
	"\fplayer_stats\x18\x06 \x03(\v2\x1d.towerdefense.PlayerGameStatsR\vplayerStats\x120\n" +
	"\x06reward\x18\a \x01(\v2\x18.towerdefense.GameRewardR\x06reward\"\x88\x02\n" +
	"\x0fPlayerGameStats\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\x12\x1d\n" +
	"\n" +
	"kill_count\x18\x03 \x01(\x05R\tkillCount\x12!\n" +
	"\ftotal_damage\x18\x04 \x01(\x03R\vtotalDamage\x12\x1f\n" +
	"\vtower_count\x18\x05 \x01(\x05R\n" +
	"towerCount\x12\x1f\n" +
	"\vgold_earned\x18\x06 \x01(\x05R\n" +
	"goldEarned\x12\x1d\n" +
	"\n" +
	"gold_spent\x18\a \x01(\x05R\tgoldSpent\x12\x14\n" +
	"\x05score\x18\b \x01(\x05R\x05score\"b\n" +
	"\n" +
	"GameReward\x12\x12\n" +
	"\x04coin\x18\x01 \x01(\x05R\x04coin\x12\x10\n" +
	"\x03exp\x18\x02 \x01(\x05R\x03exp\x12.\n" +
	"\x05items\x18\x03 \x03(\v2\x18.towerdefense.ItemRewardR\x05items\"a\n" +
	"\n" +
	"ItemReward\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x05R\x06itemId\x12\x1d\n" +
	"\n" +
	"item_count\x18\x02 \x01(\x05R\titemCount\x12\x1b\n" +
	"\titem_name\x18\x03 \x01(\tR\bitemName\"-\n" +
	"\x10PauseGameRequest\x12\x19\n" +
	"\bis_pause\x18\x01 \x01(\bR\aisPause\"b\n" +
	"\x11PauseGameResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\bis_pause\x18\x02 \x01(\bR\aisPause\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessageB)Z\x12towerdefense/proto\xaa\x02\x12TowerDefense.Protob\x06proto3"

var (
	file_battle_proto_rawDescOnce sync.Once
	file_battle_proto_rawDescData []byte
)

func file_battle_proto_rawDescGZIP() []byte {
	file_battle_proto_rawDescOnce.Do(func() {
		file_battle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_battle_proto_rawDesc), len(file_battle_proto_rawDesc)))
	})
	return file_battle_proto_rawDescData
}

var file_battle_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_battle_proto_goTypes = []any{
	(*PlaceTowerRequest)(nil),     // 0: towerdefense.PlaceTowerRequest
	(*PlaceTowerResponse)(nil),    // 1: towerdefense.PlaceTowerResponse
	(*UpgradeTowerRequest)(nil),   // 2: towerdefense.UpgradeTowerRequest
	(*UpgradeTowerResponse)(nil),  // 3: towerdefense.UpgradeTowerResponse
	(*SellTowerRequest)(nil),      // 4: towerdefense.SellTowerRequest
	(*SellTowerResponse)(nil),     // 5: towerdefense.SellTowerResponse
	(*UseSkillRequest)(nil),       // 6: towerdefense.UseSkillRequest
	(*UseSkillResponse)(nil),      // 7: towerdefense.UseSkillResponse
	(*WaveStartBroadcast)(nil),    // 8: towerdefense.WaveStartBroadcast
	(*WaveCompleteBroadcast)(nil), // 9: towerdefense.WaveCompleteBroadcast
	(*GameOverBroadcast)(nil),     // 10: towerdefense.GameOverBroadcast
	(*PlayerGameStats)(nil),       // 11: towerdefense.PlayerGameStats
	(*GameReward)(nil),            // 12: towerdefense.GameReward
	(*ItemReward)(nil),            // 13: towerdefense.ItemReward
	(*PauseGameRequest)(nil),      // 14: towerdefense.PauseGameRequest
	(*PauseGameResponse)(nil),     // 15: towerdefense.PauseGameResponse
	(*Vector3)(nil),               // 16: Vector3
}
var file_battle_proto_depIdxs = []int32{
	16, // 0: towerdefense.PlaceTowerRequest.position:type_name -> Vector3
	16, // 1: towerdefense.PlaceTowerResponse.position:type_name -> Vector3
	16, // 2: towerdefense.UseSkillRequest.target_position:type_name -> Vector3
	11, // 3: towerdefense.GameOverBroadcast.player_stats:type_name -> towerdefense.PlayerGameStats
	12, // 4: towerdefense.GameOverBroadcast.reward:type_name -> towerdefense.GameReward
	13, // 5: towerdefense.GameReward.items:type_name -> towerdefense.ItemReward
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_battle_proto_init() }
func file_battle_proto_init() {
	if File_battle_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_battle_proto_rawDesc), len(file_battle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_battle_proto_goTypes,
		DependencyIndexes: file_battle_proto_depIdxs,
		MessageInfos:      file_battle_proto_msgTypes,
	}.Build()
	File_battle_proto = out.File
	file_battle_proto_goTypes = nil
	file_battle_proto_depIdxs = nil
}
