// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: common.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_MSG_NONE MessageType = 0
	// 连接相关 1000-1099
	MessageType_MSG_HEARTBEAT MessageType = 1000
	MessageType_MSG_LOGIN     MessageType = 1001
	MessageType_MSG_LOGOUT    MessageType = 1002
	// 房间相关 2000-2099
	MessageType_MSG_CREATE_ROOM MessageType = 2001
	MessageType_MSG_JOIN_ROOM   MessageType = 2002
	MessageType_MSG_LEAVE_ROOM  MessageType = 2003
	MessageType_MSG_ROOM_INFO   MessageType = 2004
	MessageType_MSG_START_GAME  MessageType = 2005
	// 战斗相关 3000-3099
	MessageType_MSG_PLACE_TOWER   MessageType = 3001
	MessageType_MSG_UPGRADE_TOWER MessageType = 3002
	MessageType_MSG_SELL_TOWER    MessageType = 3003
	MessageType_MSG_WAVE_START    MessageType = 3004
	MessageType_MSG_WAVE_COMPLETE MessageType = 3005
	MessageType_MSG_GAME_OVER     MessageType = 3006
	// 同步相关 4000-4099
	MessageType_MSG_SYNC_STATE  MessageType = 4001
	MessageType_MSG_SYNC_ENEMY  MessageType = 4002
	MessageType_MSG_SYNC_TOWER  MessageType = 4003
	MessageType_MSG_SYNC_DAMAGE MessageType = 4004
	// 错误消息 9999
	MessageType_MSG_ERROR MessageType = 9999
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:    "MSG_NONE",
		1000: "MSG_HEARTBEAT",
		1001: "MSG_LOGIN",
		1002: "MSG_LOGOUT",
		2001: "MSG_CREATE_ROOM",
		2002: "MSG_JOIN_ROOM",
		2003: "MSG_LEAVE_ROOM",
		2004: "MSG_ROOM_INFO",
		2005: "MSG_START_GAME",
		3001: "MSG_PLACE_TOWER",
		3002: "MSG_UPGRADE_TOWER",
		3003: "MSG_SELL_TOWER",
		3004: "MSG_WAVE_START",
		3005: "MSG_WAVE_COMPLETE",
		3006: "MSG_GAME_OVER",
		4001: "MSG_SYNC_STATE",
		4002: "MSG_SYNC_ENEMY",
		4003: "MSG_SYNC_TOWER",
		4004: "MSG_SYNC_DAMAGE",
		9999: "MSG_ERROR",
	}
	MessageType_value = map[string]int32{
		"MSG_NONE":          0,
		"MSG_HEARTBEAT":     1000,
		"MSG_LOGIN":         1001,
		"MSG_LOGOUT":        1002,
		"MSG_CREATE_ROOM":   2001,
		"MSG_JOIN_ROOM":     2002,
		"MSG_LEAVE_ROOM":    2003,
		"MSG_ROOM_INFO":     2004,
		"MSG_START_GAME":    2005,
		"MSG_PLACE_TOWER":   3001,
		"MSG_UPGRADE_TOWER": 3002,
		"MSG_SELL_TOWER":    3003,
		"MSG_WAVE_START":    3004,
		"MSG_WAVE_COMPLETE": 3005,
		"MSG_GAME_OVER":     3006,
		"MSG_SYNC_STATE":    4001,
		"MSG_SYNC_ENEMY":    4002,
		"MSG_SYNC_TOWER":    4003,
		"MSG_SYNC_DAMAGE":   4004,
		"MSG_ERROR":         9999,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

// 错误码定义
type ErrorCode int32

const (
	ErrorCode_ERROR_NONE ErrorCode = 0
	// 通用错误 1000-1999
	ErrorCode_ERROR_UNKNOWN           ErrorCode = 1000
	ErrorCode_ERROR_INVALID_PARAM     ErrorCode = 1001
	ErrorCode_ERROR_PERMISSION_DENIED ErrorCode = 1002
	ErrorCode_ERROR_NOT_FOUND         ErrorCode = 1003
	ErrorCode_ERROR_ALREADY_EXISTS    ErrorCode = 1004
	ErrorCode_ERROR_TIMEOUT           ErrorCode = 1005
	// 连接错误 2000-2099
	ErrorCode_ERROR_NOT_LOGIN     ErrorCode = 2000
	ErrorCode_ERROR_LOGIN_FAILED  ErrorCode = 2001
	ErrorCode_ERROR_TOKEN_INVALID ErrorCode = 2002
	ErrorCode_ERROR_ALREADY_LOGIN ErrorCode = 2003
	// 房间错误 3000-3099
	ErrorCode_ERROR_ROOM_FULL            ErrorCode = 3000
	ErrorCode_ERROR_ROOM_NOT_FOUND       ErrorCode = 3001
	ErrorCode_ERROR_NOT_IN_ROOM          ErrorCode = 3002
	ErrorCode_ERROR_NOT_HOST             ErrorCode = 3003
	ErrorCode_ERROR_ROOM_ALREADY_STARTED ErrorCode = 3004
	// 战斗错误 4000-4099
	ErrorCode_ERROR_NOT_ENOUGH_GOLD  ErrorCode = 4000
	ErrorCode_ERROR_INVALID_POSITION ErrorCode = 4001
	ErrorCode_ERROR_TOWER_NOT_FOUND  ErrorCode = 4002
	ErrorCode_ERROR_GAME_NOT_STARTED ErrorCode = 4003
	ErrorCode_ERROR_GAME_OVER        ErrorCode = 4004
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:    "ERROR_NONE",
		1000: "ERROR_UNKNOWN",
		1001: "ERROR_INVALID_PARAM",
		1002: "ERROR_PERMISSION_DENIED",
		1003: "ERROR_NOT_FOUND",
		1004: "ERROR_ALREADY_EXISTS",
		1005: "ERROR_TIMEOUT",
		2000: "ERROR_NOT_LOGIN",
		2001: "ERROR_LOGIN_FAILED",
		2002: "ERROR_TOKEN_INVALID",
		2003: "ERROR_ALREADY_LOGIN",
		3000: "ERROR_ROOM_FULL",
		3001: "ERROR_ROOM_NOT_FOUND",
		3002: "ERROR_NOT_IN_ROOM",
		3003: "ERROR_NOT_HOST",
		3004: "ERROR_ROOM_ALREADY_STARTED",
		4000: "ERROR_NOT_ENOUGH_GOLD",
		4001: "ERROR_INVALID_POSITION",
		4002: "ERROR_TOWER_NOT_FOUND",
		4003: "ERROR_GAME_NOT_STARTED",
		4004: "ERROR_GAME_OVER",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_NONE":                 0,
		"ERROR_UNKNOWN":              1000,
		"ERROR_INVALID_PARAM":        1001,
		"ERROR_PERMISSION_DENIED":    1002,
		"ERROR_NOT_FOUND":            1003,
		"ERROR_ALREADY_EXISTS":       1004,
		"ERROR_TIMEOUT":              1005,
		"ERROR_NOT_LOGIN":            2000,
		"ERROR_LOGIN_FAILED":         2001,
		"ERROR_TOKEN_INVALID":        2002,
		"ERROR_ALREADY_LOGIN":        2003,
		"ERROR_ROOM_FULL":            3000,
		"ERROR_ROOM_NOT_FOUND":       3001,
		"ERROR_NOT_IN_ROOM":          3002,
		"ERROR_NOT_HOST":             3003,
		"ERROR_ROOM_ALREADY_STARTED": 3004,
		"ERROR_NOT_ENOUGH_GOLD":      4000,
		"ERROR_INVALID_POSITION":     4001,
		"ERROR_TOWER_NOT_FOUND":      4002,
		"ERROR_GAME_NOT_STARTED":     4003,
		"ERROR_GAME_OVER":            4004,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

// 三维向量
type Vector3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector3) Reset() {
	*x = Vector3{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector3) ProtoMessage() {}

func (x *Vector3) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector3.ProtoReflect.Descriptor instead.
func (*Vector3) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *Vector3) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector3) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vector3) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

// 网络消息包装器 - 用于 WebSocket 传输
type NetworkPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           int32                  `protobuf:"varint,1,opt,name=cmd,proto3" json:"cmd,omitempty"`                             // 对应 Cmd 枚举值
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`                           // 错误码，0表示成功
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                      // 序列化后的具体消息内容
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                 // 时间戳
	MessageId     string                 `protobuf:"bytes,5,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // 消息ID，用于追踪
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkPacket) Reset() {
	*x = NetworkPacket{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPacket) ProtoMessage() {}

func (x *NetworkPacket) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPacket.ProtoReflect.Descriptor instead.
func (*NetworkPacket) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *NetworkPacket) GetCmd() int32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *NetworkPacket) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *NetworkPacket) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *NetworkPacket) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *NetworkPacket) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

// 错误响应
type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"` // 详细错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *ErrorResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\"3\n" +
	"\aVector3\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\"\x8c\x01\n" +
	"\rNetworkPacket\x12\x10\n" +
	"\x03cmd\x18\x01 \x01(\x05R\x03cmd\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"message_id\x18\x05 \x01(\tR\tmessageId\"U\n" +
	"\rErrorResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail*\xa1\x03\n" +
	"\vMessageType\x12\f\n" +
	"\bMSG_NONE\x10\x00\x12\x12\n" +
	"\rMSG_HEARTBEAT\x10\xe8\a\x12\x0e\n" +
	"\tMSG_LOGIN\x10\xe9\a\x12\x0f\n" +
	"\n" +
	"MSG_LOGOUT\x10\xea\a\x12\x14\n" +
	"\x0fMSG_CREATE_ROOM\x10\xd1\x0f\x12\x12\n" +
	"\rMSG_JOIN_ROOM\x10\xd2\x0f\x12\x13\n" +
	"\x0eMSG_LEAVE_ROOM\x10\xd3\x0f\x12\x12\n" +
	"\rMSG_ROOM_INFO\x10\xd4\x0f\x12\x13\n" +
	"\x0eMSG_START_GAME\x10\xd5\x0f\x12\x14\n" +
	"\x0fMSG_PLACE_TOWER\x10\xb9\x17\x12\x16\n" +
	"\x11MSG_UPGRADE_TOWER\x10\xba\x17\x12\x13\n" +
	"\x0eMSG_SELL_TOWER\x10\xbb\x17\x12\x13\n" +
	"\x0eMSG_WAVE_START\x10\xbc\x17\x12\x16\n" +
	"\x11MSG_WAVE_COMPLETE\x10\xbd\x17\x12\x12\n" +
	"\rMSG_GAME_OVER\x10\xbe\x17\x12\x13\n" +
	"\x0eMSG_SYNC_STATE\x10\xa1\x1f\x12\x13\n" +
	"\x0eMSG_SYNC_ENEMY\x10\xa2\x1f\x12\x13\n" +
	"\x0eMSG_SYNC_TOWER\x10\xa3\x1f\x12\x14\n" +
	"\x0fMSG_SYNC_DAMAGE\x10\xa4\x1f\x12\x0e\n" +
	"\tMSG_ERROR\x10\x8fN*\x96\x04\n" +
	"\tErrorCode\x12\x0e\n" +
	"\n" +
	"ERROR_NONE\x10\x00\x12\x12\n" +
	"\rERROR_UNKNOWN\x10\xe8\a\x12\x18\n" +
	"\x13ERROR_INVALID_PARAM\x10\xe9\a\x12\x1c\n" +
	"\x17ERROR_PERMISSION_DENIED\x10\xea\a\x12\x14\n" +
	"\x0fERROR_NOT_FOUND\x10\xeb\a\x12\x19\n" +
	"\x14ERROR_ALREADY_EXISTS\x10\xec\a\x12\x12\n" +
	"\rERROR_TIMEOUT\x10\xed\a\x12\x14\n" +
	"\x0fERROR_NOT_LOGIN\x10\xd0\x0f\x12\x17\n" +
	"\x12ERROR_LOGIN_FAILED\x10\xd1\x0f\x12\x18\n" +
	"\x13ERROR_TOKEN_INVALID\x10\xd2\x0f\x12\x18\n" +
	"\x13ERROR_ALREADY_LOGIN\x10\xd3\x0f\x12\x14\n" +
	"\x0fERROR_ROOM_FULL\x10\xb8\x17\x12\x19\n" +
	"\x14ERROR_ROOM_NOT_FOUND\x10\xb9\x17\x12\x16\n" +
	"\x11ERROR_NOT_IN_ROOM\x10\xba\x17\x12\x13\n" +
	"\x0eERROR_NOT_HOST\x10\xbb\x17\x12\x1f\n" +
	"\x1aERROR_ROOM_ALREADY_STARTED\x10\xbc\x17\x12\x1a\n" +
	"\x15ERROR_NOT_ENOUGH_GOLD\x10\xa0\x1f\x12\x1b\n" +
	"\x16ERROR_INVALID_POSITION\x10\xa1\x1f\x12\x1a\n" +
	"\x15ERROR_TOWER_NOT_FOUND\x10\xa2\x1f\x12\x1b\n" +
	"\x16ERROR_GAME_NOT_STARTED\x10\xa3\x1f\x12\x14\n" +
	"\x0fERROR_GAME_OVER\x10\xa4\x1fB)Z\x12towerdefense/proto\xaa\x02\x12TowerDefense.Protob\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_common_proto_goTypes = []any{
	(MessageType)(0),      // 0: MessageType
	(ErrorCode)(0),        // 1: ErrorCode
	(*Vector3)(nil),       // 2: Vector3
	(*NetworkPacket)(nil), // 3: NetworkPacket
	(*ErrorResponse)(nil), // 4: ErrorResponse
}
var file_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
