// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: player.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 玩家完整数据
type PlayerData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`                    // 玩家ID
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`              // 玩家名称
	IconId        int32                  `protobuf:"varint,3,opt,name=icon_id,json=iconId,proto3" json:"icon_id,omitempty"`                         // 头像ID
	FrameId       int32                  `protobuf:"varint,4,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`                      // 头像框ID
	Level         int32                  `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`                                         // 等级
	Exp           int32                  `protobuf:"varint,6,opt,name=exp,proto3" json:"exp,omitempty"`                                             // 经验值
	Gold          int32                  `protobuf:"varint,7,opt,name=gold,proto3" json:"gold,omitempty"`                                           // 金币
	Diamond       int32                  `protobuf:"varint,8,opt,name=diamond,proto3" json:"diamond,omitempty"`                                     // 钻石
	VipLevel      int32                  `protobuf:"varint,9,opt,name=vip_level,json=vipLevel,proto3" json:"vip_level,omitempty"`                   // VIP等级
	TotalBattles  int32                  `protobuf:"varint,10,opt,name=total_battles,json=totalBattles,proto3" json:"total_battles,omitempty"`      // 总战斗次数
	WinCount      int32                  `protobuf:"varint,11,opt,name=win_count,json=winCount,proto3" json:"win_count,omitempty"`                  // 胜利次数
	LoseCount     int32                  `protobuf:"varint,12,opt,name=lose_count,json=loseCount,proto3" json:"lose_count,omitempty"`               // 失败次数
	TotalKills    int32                  `protobuf:"varint,13,opt,name=total_kills,json=totalKills,proto3" json:"total_kills,omitempty"`            // 总击杀数
	MaxWave       int32                  `protobuf:"varint,14,opt,name=max_wave,json=maxWave,proto3" json:"max_wave,omitempty"`                     // 最高波数
	CreateTime    int64                  `protobuf:"varint,15,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`            // 创建时间（时间戳）
	LastLoginTime int64                  `protobuf:"varint,16,opt,name=last_login_time,json=lastLoginTime,proto3" json:"last_login_time,omitempty"` // 最后登录时间（时间戳）
	IsNewPlayer   bool                   `protobuf:"varint,17,opt,name=is_new_player,json=isNewPlayer,proto3" json:"is_new_player,omitempty"`       // 是否新玩家（刚创建角色）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerData) Reset() {
	*x = PlayerData{}
	mi := &file_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerData) ProtoMessage() {}

func (x *PlayerData) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerData.ProtoReflect.Descriptor instead.
func (*PlayerData) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerData) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerData) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *PlayerData) GetIconId() int32 {
	if x != nil {
		return x.IconId
	}
	return 0
}

func (x *PlayerData) GetFrameId() int32 {
	if x != nil {
		return x.FrameId
	}
	return 0
}

func (x *PlayerData) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PlayerData) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *PlayerData) GetGold() int32 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *PlayerData) GetDiamond() int32 {
	if x != nil {
		return x.Diamond
	}
	return 0
}

func (x *PlayerData) GetVipLevel() int32 {
	if x != nil {
		return x.VipLevel
	}
	return 0
}

func (x *PlayerData) GetTotalBattles() int32 {
	if x != nil {
		return x.TotalBattles
	}
	return 0
}

func (x *PlayerData) GetWinCount() int32 {
	if x != nil {
		return x.WinCount
	}
	return 0
}

func (x *PlayerData) GetLoseCount() int32 {
	if x != nil {
		return x.LoseCount
	}
	return 0
}

func (x *PlayerData) GetTotalKills() int32 {
	if x != nil {
		return x.TotalKills
	}
	return 0
}

func (x *PlayerData) GetMaxWave() int32 {
	if x != nil {
		return x.MaxWave
	}
	return 0
}

func (x *PlayerData) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *PlayerData) GetLastLoginTime() int64 {
	if x != nil {
		return x.LastLoginTime
	}
	return 0
}

func (x *PlayerData) GetIsNewPlayer() bool {
	if x != nil {
		return x.IsNewPlayer
	}
	return false
}

// 获取玩家数据请求
type GetPlayerDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerDataRequest) Reset() {
	*x = GetPlayerDataRequest{}
	mi := &file_player_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerDataRequest) ProtoMessage() {}

func (x *GetPlayerDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerDataRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerDataRequest) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{1}
}

// 获取玩家数据响应
type GetPlayerDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PlayerData    *PlayerData            `protobuf:"bytes,3,opt,name=player_data,json=playerData,proto3" json:"player_data,omitempty"` // 玩家数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerDataResponse) Reset() {
	*x = GetPlayerDataResponse{}
	mi := &file_player_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerDataResponse) ProtoMessage() {}

func (x *GetPlayerDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerDataResponse.ProtoReflect.Descriptor instead.
func (*GetPlayerDataResponse) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{2}
}

func (x *GetPlayerDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetPlayerDataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetPlayerDataResponse) GetPlayerData() *PlayerData {
	if x != nil {
		return x.PlayerData
	}
	return nil
}

// 修改玩家名请求
type UpdatePlayerNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewName       string                 `protobuf:"bytes,1,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"` // 新名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlayerNameRequest) Reset() {
	*x = UpdatePlayerNameRequest{}
	mi := &file_player_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlayerNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlayerNameRequest) ProtoMessage() {}

func (x *UpdatePlayerNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlayerNameRequest.ProtoReflect.Descriptor instead.
func (*UpdatePlayerNameRequest) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{3}
}

func (x *UpdatePlayerNameRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

// 修改玩家名响应
type UpdatePlayerNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NewName       string                 `protobuf:"bytes,3,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"` // 修改后的名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlayerNameResponse) Reset() {
	*x = UpdatePlayerNameResponse{}
	mi := &file_player_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlayerNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlayerNameResponse) ProtoMessage() {}

func (x *UpdatePlayerNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlayerNameResponse.ProtoReflect.Descriptor instead.
func (*UpdatePlayerNameResponse) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePlayerNameResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdatePlayerNameResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdatePlayerNameResponse) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

// 修改头像请求
type UpdatePlayerIconRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IconId        int32                  `protobuf:"varint,1,opt,name=icon_id,json=iconId,proto3" json:"icon_id,omitempty"` // 新头像ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlayerIconRequest) Reset() {
	*x = UpdatePlayerIconRequest{}
	mi := &file_player_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlayerIconRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlayerIconRequest) ProtoMessage() {}

func (x *UpdatePlayerIconRequest) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlayerIconRequest.ProtoReflect.Descriptor instead.
func (*UpdatePlayerIconRequest) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePlayerIconRequest) GetIconId() int32 {
	if x != nil {
		return x.IconId
	}
	return 0
}

// 修改头像响应
type UpdatePlayerIconResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	IconId        int32                  `protobuf:"varint,3,opt,name=icon_id,json=iconId,proto3" json:"icon_id,omitempty"` // 修改后的头像ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlayerIconResponse) Reset() {
	*x = UpdatePlayerIconResponse{}
	mi := &file_player_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlayerIconResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlayerIconResponse) ProtoMessage() {}

func (x *UpdatePlayerIconResponse) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlayerIconResponse.ProtoReflect.Descriptor instead.
func (*UpdatePlayerIconResponse) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePlayerIconResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdatePlayerIconResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdatePlayerIconResponse) GetIconId() int32 {
	if x != nil {
		return x.IconId
	}
	return 0
}

var File_player_proto protoreflect.FileDescriptor

const file_player_proto_rawDesc = "" +
	"\n" +
	"\fplayer.proto\"\xfb\x03\n" +
	"\n" +
	"PlayerData\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\x12\x17\n" +
	"\aicon_id\x18\x03 \x01(\x05R\x06iconId\x12\x19\n" +
	"\bframe_id\x18\x04 \x01(\x05R\aframeId\x12\x14\n" +
	"\x05level\x18\x05 \x01(\x05R\x05level\x12\x10\n" +
	"\x03exp\x18\x06 \x01(\x05R\x03exp\x12\x12\n" +
	"\x04gold\x18\a \x01(\x05R\x04gold\x12\x18\n" +
	"\adiamond\x18\b \x01(\x05R\adiamond\x12\x1b\n" +
	"\tvip_level\x18\t \x01(\x05R\bvipLevel\x12#\n" +
	"\rtotal_battles\x18\n" +
	" \x01(\x05R\ftotalBattles\x12\x1b\n" +
	"\twin_count\x18\v \x01(\x05R\bwinCount\x12\x1d\n" +
	"\n" +
	"lose_count\x18\f \x01(\x05R\tloseCount\x12\x1f\n" +
	"\vtotal_kills\x18\r \x01(\x05R\n" +
	"totalKills\x12\x19\n" +
	"\bmax_wave\x18\x0e \x01(\x05R\amaxWave\x12\x1f\n" +
	"\vcreate_time\x18\x0f \x01(\x03R\n" +
	"createTime\x12&\n" +
	"\x0flast_login_time\x18\x10 \x01(\x03R\rlastLoginTime\x12\"\n" +
	"\ris_new_player\x18\x11 \x01(\bR\visNewPlayer\"\x16\n" +
	"\x14GetPlayerDataRequest\"y\n" +
	"\x15GetPlayerDataResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12,\n" +
	"\vplayer_data\x18\x03 \x01(\v2\v.PlayerDataR\n" +
	"playerData\"4\n" +
	"\x17UpdatePlayerNameRequest\x12\x19\n" +
	"\bnew_name\x18\x01 \x01(\tR\anewName\"i\n" +
	"\x18UpdatePlayerNameResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bnew_name\x18\x03 \x01(\tR\anewName\"2\n" +
	"\x17UpdatePlayerIconRequest\x12\x17\n" +
	"\aicon_id\x18\x01 \x01(\x05R\x06iconId\"g\n" +
	"\x18UpdatePlayerIconResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\aicon_id\x18\x03 \x01(\x05R\x06iconIdB)Z\x12towerdefense/proto\xaa\x02\x12TowerDefense.Protob\x06proto3"

var (
	file_player_proto_rawDescOnce sync.Once
	file_player_proto_rawDescData []byte
)

func file_player_proto_rawDescGZIP() []byte {
	file_player_proto_rawDescOnce.Do(func() {
		file_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_player_proto_rawDesc), len(file_player_proto_rawDesc)))
	})
	return file_player_proto_rawDescData
}

var file_player_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_player_proto_goTypes = []any{
	(*PlayerData)(nil),               // 0: PlayerData
	(*GetPlayerDataRequest)(nil),     // 1: GetPlayerDataRequest
	(*GetPlayerDataResponse)(nil),    // 2: GetPlayerDataResponse
	(*UpdatePlayerNameRequest)(nil),  // 3: UpdatePlayerNameRequest
	(*UpdatePlayerNameResponse)(nil), // 4: UpdatePlayerNameResponse
	(*UpdatePlayerIconRequest)(nil),  // 5: UpdatePlayerIconRequest
	(*UpdatePlayerIconResponse)(nil), // 6: UpdatePlayerIconResponse
}
var file_player_proto_depIdxs = []int32{
	0, // 0: GetPlayerDataResponse.player_data:type_name -> PlayerData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_player_proto_init() }
func file_player_proto_init() {
	if File_player_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_player_proto_rawDesc), len(file_player_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_player_proto_goTypes,
		DependencyIndexes: file_player_proto_depIdxs,
		MessageInfos:      file_player_proto_msgTypes,
	}.Build()
	File_player_proto = out.File
	file_player_proto_goTypes = nil
	file_player_proto_depIdxs = nil
}
