// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: sync.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 敌人状态
type EnemyState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnemyId       string                 `protobuf:"bytes,1,opt,name=enemy_id,json=enemyId,proto3" json:"enemy_id,omitempty"`
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Hp            int32                  `protobuf:"varint,3,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxHp         int32                  `protobuf:"varint,4,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	Position      *Vector3               `protobuf:"bytes,5,opt,name=position,proto3" json:"position,omitempty"`
	Speed         float32                `protobuf:"fixed32,6,opt,name=speed,proto3" json:"speed,omitempty"`
	PathIndex     int32                  `protobuf:"varint,7,opt,name=path_index,json=pathIndex,proto3" json:"path_index,omitempty"`           // 路径点索引
	PathProgress  float32                `protobuf:"fixed32,8,opt,name=path_progress,json=pathProgress,proto3" json:"path_progress,omitempty"` // 路径进度 0-1
	Buffs         []int32                `protobuf:"varint,9,rep,packed,name=buffs,proto3" json:"buffs,omitempty"`                             // Buff列表
	Debuffs       []int32                `protobuf:"varint,10,rep,packed,name=debuffs,proto3" json:"debuffs,omitempty"`                        // Debuff列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnemyState) Reset() {
	*x = EnemyState{}
	mi := &file_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnemyState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnemyState) ProtoMessage() {}

func (x *EnemyState) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnemyState.ProtoReflect.Descriptor instead.
func (*EnemyState) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{0}
}

func (x *EnemyState) GetEnemyId() string {
	if x != nil {
		return x.EnemyId
	}
	return ""
}

func (x *EnemyState) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *EnemyState) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *EnemyState) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *EnemyState) GetPosition() *Vector3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *EnemyState) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *EnemyState) GetPathIndex() int32 {
	if x != nil {
		return x.PathIndex
	}
	return 0
}

func (x *EnemyState) GetPathProgress() float32 {
	if x != nil {
		return x.PathProgress
	}
	return 0
}

func (x *EnemyState) GetBuffs() []int32 {
	if x != nil {
		return x.Buffs
	}
	return nil
}

func (x *EnemyState) GetDebuffs() []int32 {
	if x != nil {
		return x.Debuffs
	}
	return nil
}

// 防御塔状态
type TowerState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TowerId        string                 `protobuf:"bytes,1,opt,name=tower_id,json=towerId,proto3" json:"tower_id,omitempty"`
	Type           int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Level          int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Position       *Vector3               `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	TargetId       string                 `protobuf:"bytes,5,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`                     // 当前目标ID
	AttackCooldown float32                `protobuf:"fixed32,6,opt,name=attack_cooldown,json=attackCooldown,proto3" json:"attack_cooldown,omitempty"` // 攻击冷却剩余时间
	TotalDamage    int32                  `protobuf:"varint,7,opt,name=total_damage,json=totalDamage,proto3" json:"total_damage,omitempty"`           // 累计伤害
	KillCount      int32                  `protobuf:"varint,8,opt,name=kill_count,json=killCount,proto3" json:"kill_count,omitempty"`                 // 击杀数
	OwnerId        string                 `protobuf:"bytes,9,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`                        // 所属玩家ID
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TowerState) Reset() {
	*x = TowerState{}
	mi := &file_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TowerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TowerState) ProtoMessage() {}

func (x *TowerState) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TowerState.ProtoReflect.Descriptor instead.
func (*TowerState) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{1}
}

func (x *TowerState) GetTowerId() string {
	if x != nil {
		return x.TowerId
	}
	return ""
}

func (x *TowerState) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *TowerState) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *TowerState) GetPosition() *Vector3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *TowerState) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *TowerState) GetAttackCooldown() float32 {
	if x != nil {
		return x.AttackCooldown
	}
	return 0
}

func (x *TowerState) GetTotalDamage() int32 {
	if x != nil {
		return x.TotalDamage
	}
	return 0
}

func (x *TowerState) GetKillCount() int32 {
	if x != nil {
		return x.KillCount
	}
	return 0
}

func (x *TowerState) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

// 状态同步广播
type SyncStateBroadcast struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Gold             int32                  `protobuf:"varint,1,opt,name=gold,proto3" json:"gold,omitempty"`
	Life             int32                  `protobuf:"varint,2,opt,name=life,proto3" json:"life,omitempty"`
	WaveNum          int32                  `protobuf:"varint,3,opt,name=wave_num,json=waveNum,proto3" json:"wave_num,omitempty"`
	Enemies          []*EnemyState          `protobuf:"bytes,4,rep,name=enemies,proto3" json:"enemies,omitempty"`
	Towers           []*TowerState          `protobuf:"bytes,5,rep,name=towers,proto3" json:"towers,omitempty"`
	GameTime         float32                `protobuf:"fixed32,6,opt,name=game_time,json=gameTime,proto3" json:"game_time,omitempty"`                          // 游戏时间
	CurrentWaveKills int32                  `protobuf:"varint,7,opt,name=current_wave_kills,json=currentWaveKills,proto3" json:"current_wave_kills,omitempty"` // 当前波击杀数
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SyncStateBroadcast) Reset() {
	*x = SyncStateBroadcast{}
	mi := &file_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncStateBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStateBroadcast) ProtoMessage() {}

func (x *SyncStateBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStateBroadcast.ProtoReflect.Descriptor instead.
func (*SyncStateBroadcast) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{2}
}

func (x *SyncStateBroadcast) GetGold() int32 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *SyncStateBroadcast) GetLife() int32 {
	if x != nil {
		return x.Life
	}
	return 0
}

func (x *SyncStateBroadcast) GetWaveNum() int32 {
	if x != nil {
		return x.WaveNum
	}
	return 0
}

func (x *SyncStateBroadcast) GetEnemies() []*EnemyState {
	if x != nil {
		return x.Enemies
	}
	return nil
}

func (x *SyncStateBroadcast) GetTowers() []*TowerState {
	if x != nil {
		return x.Towers
	}
	return nil
}

func (x *SyncStateBroadcast) GetGameTime() float32 {
	if x != nil {
		return x.GameTime
	}
	return 0
}

func (x *SyncStateBroadcast) GetCurrentWaveKills() int32 {
	if x != nil {
		return x.CurrentWaveKills
	}
	return 0
}

// 敌人同步广播
type SyncEnemyBroadcast struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Enemies         []*EnemyState          `protobuf:"bytes,1,rep,name=enemies,proto3" json:"enemies,omitempty"`
	RemovedEnemyIds []string               `protobuf:"bytes,2,rep,name=removed_enemy_ids,json=removedEnemyIds,proto3" json:"removed_enemy_ids,omitempty"` // 已移除的敌人ID列表
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SyncEnemyBroadcast) Reset() {
	*x = SyncEnemyBroadcast{}
	mi := &file_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncEnemyBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncEnemyBroadcast) ProtoMessage() {}

func (x *SyncEnemyBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncEnemyBroadcast.ProtoReflect.Descriptor instead.
func (*SyncEnemyBroadcast) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{3}
}

func (x *SyncEnemyBroadcast) GetEnemies() []*EnemyState {
	if x != nil {
		return x.Enemies
	}
	return nil
}

func (x *SyncEnemyBroadcast) GetRemovedEnemyIds() []string {
	if x != nil {
		return x.RemovedEnemyIds
	}
	return nil
}

// 防御塔同步广播
type SyncTowerBroadcast struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Towers          []*TowerState          `protobuf:"bytes,1,rep,name=towers,proto3" json:"towers,omitempty"`
	RemovedTowerIds []string               `protobuf:"bytes,2,rep,name=removed_tower_ids,json=removedTowerIds,proto3" json:"removed_tower_ids,omitempty"` // 已移除的塔ID列表
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SyncTowerBroadcast) Reset() {
	*x = SyncTowerBroadcast{}
	mi := &file_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncTowerBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncTowerBroadcast) ProtoMessage() {}

func (x *SyncTowerBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncTowerBroadcast.ProtoReflect.Descriptor instead.
func (*SyncTowerBroadcast) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{4}
}

func (x *SyncTowerBroadcast) GetTowers() []*TowerState {
	if x != nil {
		return x.Towers
	}
	return nil
}

func (x *SyncTowerBroadcast) GetRemovedTowerIds() []string {
	if x != nil {
		return x.RemovedTowerIds
	}
	return nil
}

// 伤害同步广播
type SyncDamageBroadcast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TowerId       string                 `protobuf:"bytes,1,opt,name=tower_id,json=towerId,proto3" json:"tower_id,omitempty"`
	EnemyId       string                 `protobuf:"bytes,2,opt,name=enemy_id,json=enemyId,proto3" json:"enemy_id,omitempty"`
	Damage        int32                  `protobuf:"varint,3,opt,name=damage,proto3" json:"damage,omitempty"`
	IsCrit        bool                   `protobuf:"varint,4,opt,name=is_crit,json=isCrit,proto3" json:"is_crit,omitempty"`
	IsKill        bool                   `protobuf:"varint,5,opt,name=is_kill,json=isKill,proto3" json:"is_kill,omitempty"`
	Position      *Vector3               `protobuf:"bytes,6,opt,name=position,proto3" json:"position,omitempty"`                        // 伤害位置
	DamageType    int32                  `protobuf:"varint,7,opt,name=damage_type,json=damageType,proto3" json:"damage_type,omitempty"` // 伤害类型: 1=物理 2=魔法 3=真实
	Effects       []int32                `protobuf:"varint,8,rep,packed,name=effects,proto3" json:"effects,omitempty"`                  // 伤害特效列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncDamageBroadcast) Reset() {
	*x = SyncDamageBroadcast{}
	mi := &file_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncDamageBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncDamageBroadcast) ProtoMessage() {}

func (x *SyncDamageBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncDamageBroadcast.ProtoReflect.Descriptor instead.
func (*SyncDamageBroadcast) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{5}
}

func (x *SyncDamageBroadcast) GetTowerId() string {
	if x != nil {
		return x.TowerId
	}
	return ""
}

func (x *SyncDamageBroadcast) GetEnemyId() string {
	if x != nil {
		return x.EnemyId
	}
	return ""
}

func (x *SyncDamageBroadcast) GetDamage() int32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *SyncDamageBroadcast) GetIsCrit() bool {
	if x != nil {
		return x.IsCrit
	}
	return false
}

func (x *SyncDamageBroadcast) GetIsKill() bool {
	if x != nil {
		return x.IsKill
	}
	return false
}

func (x *SyncDamageBroadcast) GetPosition() *Vector3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *SyncDamageBroadcast) GetDamageType() int32 {
	if x != nil {
		return x.DamageType
	}
	return 0
}

func (x *SyncDamageBroadcast) GetEffects() []int32 {
	if x != nil {
		return x.Effects
	}
	return nil
}

// 敌人生成通知
type EnemySpawnNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enemy         *EnemyState            `protobuf:"bytes,1,opt,name=enemy,proto3" json:"enemy,omitempty"`
	WaveNum       int32                  `protobuf:"varint,2,opt,name=wave_num,json=waveNum,proto3" json:"wave_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnemySpawnNotify) Reset() {
	*x = EnemySpawnNotify{}
	mi := &file_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnemySpawnNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnemySpawnNotify) ProtoMessage() {}

func (x *EnemySpawnNotify) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnemySpawnNotify.ProtoReflect.Descriptor instead.
func (*EnemySpawnNotify) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{6}
}

func (x *EnemySpawnNotify) GetEnemy() *EnemyState {
	if x != nil {
		return x.Enemy
	}
	return nil
}

func (x *EnemySpawnNotify) GetWaveNum() int32 {
	if x != nil {
		return x.WaveNum
	}
	return 0
}

// 敌人死亡通知
type EnemyDeathNotify struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EnemyId        string                 `protobuf:"bytes,1,opt,name=enemy_id,json=enemyId,proto3" json:"enemy_id,omitempty"`
	KillerTowerId  string                 `protobuf:"bytes,2,opt,name=killer_tower_id,json=killerTowerId,proto3" json:"killer_tower_id,omitempty"`
	KillerPlayerId string                 `protobuf:"bytes,3,opt,name=killer_player_id,json=killerPlayerId,proto3" json:"killer_player_id,omitempty"`
	RewardGold     int32                  `protobuf:"varint,4,opt,name=reward_gold,json=rewardGold,proto3" json:"reward_gold,omitempty"`
	DeathPosition  *Vector3               `protobuf:"bytes,5,opt,name=death_position,json=deathPosition,proto3" json:"death_position,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EnemyDeathNotify) Reset() {
	*x = EnemyDeathNotify{}
	mi := &file_sync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnemyDeathNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnemyDeathNotify) ProtoMessage() {}

func (x *EnemyDeathNotify) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnemyDeathNotify.ProtoReflect.Descriptor instead.
func (*EnemyDeathNotify) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{7}
}

func (x *EnemyDeathNotify) GetEnemyId() string {
	if x != nil {
		return x.EnemyId
	}
	return ""
}

func (x *EnemyDeathNotify) GetKillerTowerId() string {
	if x != nil {
		return x.KillerTowerId
	}
	return ""
}

func (x *EnemyDeathNotify) GetKillerPlayerId() string {
	if x != nil {
		return x.KillerPlayerId
	}
	return ""
}

func (x *EnemyDeathNotify) GetRewardGold() int32 {
	if x != nil {
		return x.RewardGold
	}
	return 0
}

func (x *EnemyDeathNotify) GetDeathPosition() *Vector3 {
	if x != nil {
		return x.DeathPosition
	}
	return nil
}

// 防御塔攻击通知
type TowerAttackNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TowerId       string                 `protobuf:"bytes,1,opt,name=tower_id,json=towerId,proto3" json:"tower_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	FromPosition  *Vector3               `protobuf:"bytes,3,opt,name=from_position,json=fromPosition,proto3" json:"from_position,omitempty"`
	ToPosition    *Vector3               `protobuf:"bytes,4,opt,name=to_position,json=toPosition,proto3" json:"to_position,omitempty"`
	AttackType    int32                  `protobuf:"varint,5,opt,name=attack_type,json=attackType,proto3" json:"attack_type,omitempty"` // 攻击类型: 1=单体 2=AOE 3=链式
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TowerAttackNotify) Reset() {
	*x = TowerAttackNotify{}
	mi := &file_sync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TowerAttackNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TowerAttackNotify) ProtoMessage() {}

func (x *TowerAttackNotify) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TowerAttackNotify.ProtoReflect.Descriptor instead.
func (*TowerAttackNotify) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{8}
}

func (x *TowerAttackNotify) GetTowerId() string {
	if x != nil {
		return x.TowerId
	}
	return ""
}

func (x *TowerAttackNotify) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *TowerAttackNotify) GetFromPosition() *Vector3 {
	if x != nil {
		return x.FromPosition
	}
	return nil
}

func (x *TowerAttackNotify) GetToPosition() *Vector3 {
	if x != nil {
		return x.ToPosition
	}
	return nil
}

func (x *TowerAttackNotify) GetAttackType() int32 {
	if x != nil {
		return x.AttackType
	}
	return 0
}

// 玩家状态同步
type PlayerStateSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Gold          int32                  `protobuf:"varint,2,opt,name=gold,proto3" json:"gold,omitempty"`
	Life          int32                  `protobuf:"varint,3,opt,name=life,proto3" json:"life,omitempty"`
	KillCount     int32                  `protobuf:"varint,4,opt,name=kill_count,json=killCount,proto3" json:"kill_count,omitempty"`
	TotalDamage   int64                  `protobuf:"varint,5,opt,name=total_damage,json=totalDamage,proto3" json:"total_damage,omitempty"`
	TowerCount    int32                  `protobuf:"varint,6,opt,name=tower_count,json=towerCount,proto3" json:"tower_count,omitempty"`
	IsAlive       bool                   `protobuf:"varint,7,opt,name=is_alive,json=isAlive,proto3" json:"is_alive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerStateSync) Reset() {
	*x = PlayerStateSync{}
	mi := &file_sync_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerStateSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerStateSync) ProtoMessage() {}

func (x *PlayerStateSync) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerStateSync.ProtoReflect.Descriptor instead.
func (*PlayerStateSync) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{9}
}

func (x *PlayerStateSync) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerStateSync) GetGold() int32 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *PlayerStateSync) GetLife() int32 {
	if x != nil {
		return x.Life
	}
	return 0
}

func (x *PlayerStateSync) GetKillCount() int32 {
	if x != nil {
		return x.KillCount
	}
	return 0
}

func (x *PlayerStateSync) GetTotalDamage() int64 {
	if x != nil {
		return x.TotalDamage
	}
	return 0
}

func (x *PlayerStateSync) GetTowerCount() int32 {
	if x != nil {
		return x.TowerCount
	}
	return 0
}

func (x *PlayerStateSync) GetIsAlive() bool {
	if x != nil {
		return x.IsAlive
	}
	return false
}

// 游戏状态快照（用于断线重连）
type GameStateSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WaveNum       int32                  `protobuf:"varint,1,opt,name=wave_num,json=waveNum,proto3" json:"wave_num,omitempty"`
	GameTime      float32                `protobuf:"fixed32,2,opt,name=game_time,json=gameTime,proto3" json:"game_time,omitempty"`
	Enemies       []*EnemyState          `protobuf:"bytes,3,rep,name=enemies,proto3" json:"enemies,omitempty"`
	Towers        []*TowerState          `protobuf:"bytes,4,rep,name=towers,proto3" json:"towers,omitempty"`
	Players       []*PlayerStateSync     `protobuf:"bytes,5,rep,name=players,proto3" json:"players,omitempty"`
	GameStatus    string                 `protobuf:"bytes,6,opt,name=game_status,json=gameStatus,proto3" json:"game_status,omitempty"` // running/paused/finished
	SnapshotTime  int64                  `protobuf:"varint,7,opt,name=snapshot_time,json=snapshotTime,proto3" json:"snapshot_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameStateSnapshot) Reset() {
	*x = GameStateSnapshot{}
	mi := &file_sync_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStateSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStateSnapshot) ProtoMessage() {}

func (x *GameStateSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStateSnapshot.ProtoReflect.Descriptor instead.
func (*GameStateSnapshot) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{10}
}

func (x *GameStateSnapshot) GetWaveNum() int32 {
	if x != nil {
		return x.WaveNum
	}
	return 0
}

func (x *GameStateSnapshot) GetGameTime() float32 {
	if x != nil {
		return x.GameTime
	}
	return 0
}

func (x *GameStateSnapshot) GetEnemies() []*EnemyState {
	if x != nil {
		return x.Enemies
	}
	return nil
}

func (x *GameStateSnapshot) GetTowers() []*TowerState {
	if x != nil {
		return x.Towers
	}
	return nil
}

func (x *GameStateSnapshot) GetPlayers() []*PlayerStateSync {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GameStateSnapshot) GetGameStatus() string {
	if x != nil {
		return x.GameStatus
	}
	return ""
}

func (x *GameStateSnapshot) GetSnapshotTime() int64 {
	if x != nil {
		return x.SnapshotTime
	}
	return 0
}

// 请求游戏状态
type RequestGameStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestGameStateRequest) Reset() {
	*x = RequestGameStateRequest{}
	mi := &file_sync_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestGameStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGameStateRequest) ProtoMessage() {}

func (x *RequestGameStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGameStateRequest.ProtoReflect.Descriptor instead.
func (*RequestGameStateRequest) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{11}
}

// 游戏状态响应
type RequestGameStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Snapshot      *GameStateSnapshot     `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestGameStateResponse) Reset() {
	*x = RequestGameStateResponse{}
	mi := &file_sync_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestGameStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGameStateResponse) ProtoMessage() {}

func (x *RequestGameStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGameStateResponse.ProtoReflect.Descriptor instead.
func (*RequestGameStateResponse) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{12}
}

func (x *RequestGameStateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RequestGameStateResponse) GetSnapshot() *GameStateSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *RequestGameStateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Buff/Debuff 状态
type BuffState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuffId        int32                  `protobuf:"varint,1,opt,name=buff_id,json=buffId,proto3" json:"buff_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`        // 目标ID（敌人或塔）
	Duration      int32                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`                       // 持续时间(ms)
	StackCount    int32                  `protobuf:"varint,4,opt,name=stack_count,json=stackCount,proto3" json:"stack_count,omitempty"` // 叠加层数
	SourceId      string                 `protobuf:"bytes,5,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`        // 来源ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuffState) Reset() {
	*x = BuffState{}
	mi := &file_sync_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuffState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuffState) ProtoMessage() {}

func (x *BuffState) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuffState.ProtoReflect.Descriptor instead.
func (*BuffState) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{13}
}

func (x *BuffState) GetBuffId() int32 {
	if x != nil {
		return x.BuffId
	}
	return 0
}

func (x *BuffState) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *BuffState) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *BuffState) GetStackCount() int32 {
	if x != nil {
		return x.StackCount
	}
	return 0
}

func (x *BuffState) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

// Buff同步通知
type BuffSyncNotify struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Buffs          []*BuffState           `protobuf:"bytes,1,rep,name=buffs,proto3" json:"buffs,omitempty"`
	RemovedBuffIds []string               `protobuf:"bytes,2,rep,name=removed_buff_ids,json=removedBuffIds,proto3" json:"removed_buff_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BuffSyncNotify) Reset() {
	*x = BuffSyncNotify{}
	mi := &file_sync_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuffSyncNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuffSyncNotify) ProtoMessage() {}

func (x *BuffSyncNotify) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuffSyncNotify.ProtoReflect.Descriptor instead.
func (*BuffSyncNotify) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{14}
}

func (x *BuffSyncNotify) GetBuffs() []*BuffState {
	if x != nil {
		return x.Buffs
	}
	return nil
}

func (x *BuffSyncNotify) GetRemovedBuffIds() []string {
	if x != nil {
		return x.RemovedBuffIds
	}
	return nil
}

var File_sync_proto protoreflect.FileDescriptor

const file_sync_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"sync.proto\x12\ftowerdefense\x1a\fcommon.proto\"\x92\x02\n" +
	"\n" +
	"EnemyState\x12\x19\n" +
	"\benemy_id\x18\x01 \x01(\tR\aenemyId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x0e\n" +
	"\x02hp\x18\x03 \x01(\x05R\x02hp\x12\x15\n" +
	"\x06max_hp\x18\x04 \x01(\x05R\x05maxHp\x12$\n" +
	"\bposition\x18\x05 \x01(\v2\b.Vector3R\bposition\x12\x14\n" +
	"\x05speed\x18\x06 \x01(\x02R\x05speed\x12\x1d\n" +
	"\n" +
	"path_index\x18\a \x01(\x05R\tpathIndex\x12#\n" +
	"\rpath_progress\x18\b \x01(\x02R\fpathProgress\x12\x14\n" +
	"\x05buffs\x18\t \x03(\x05R\x05buffs\x12\x18\n" +
	"\adebuffs\x18\n" +
	" \x03(\x05R\adebuffs\"\x9a\x02\n" +
	"\n" +
	"TowerState\x12\x19\n" +
	"\btower_id\x18\x01 \x01(\tR\atowerId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12$\n" +
	"\bposition\x18\x04 \x01(\v2\b.Vector3R\bposition\x12\x1b\n" +
	"\ttarget_id\x18\x05 \x01(\tR\btargetId\x12'\n" +
	"\x0fattack_cooldown\x18\x06 \x01(\x02R\x0eattackCooldown\x12!\n" +
	"\ftotal_damage\x18\a \x01(\x05R\vtotalDamage\x12\x1d\n" +
	"\n" +
	"kill_count\x18\b \x01(\x05R\tkillCount\x12\x19\n" +
	"\bowner_id\x18\t \x01(\tR\aownerId\"\x88\x02\n" +
	"\x12SyncStateBroadcast\x12\x12\n" +
	"\x04gold\x18\x01 \x01(\x05R\x04gold\x12\x12\n" +
	"\x04life\x18\x02 \x01(\x05R\x04life\x12\x19\n" +
	"\bwave_num\x18\x03 \x01(\x05R\awaveNum\x122\n" +
	"\aenemies\x18\x04 \x03(\v2\x18.towerdefense.EnemyStateR\aenemies\x120\n" +
	"\x06towers\x18\x05 \x03(\v2\x18.towerdefense.TowerStateR\x06towers\x12\x1b\n" +
	"\tgame_time\x18\x06 \x01(\x02R\bgameTime\x12,\n" +
	"\x12current_wave_kills\x18\a \x01(\x05R\x10currentWaveKills\"t\n" +
	"\x12SyncEnemyBroadcast\x122\n" +
	"\aenemies\x18\x01 \x03(\v2\x18.towerdefense.EnemyStateR\aenemies\x12*\n" +
	"\x11removed_enemy_ids\x18\x02 \x03(\tR\x0fremovedEnemyIds\"r\n" +
	"\x12SyncTowerBroadcast\x120\n" +
	"\x06towers\x18\x01 \x03(\v2\x18.towerdefense.TowerStateR\x06towers\x12*\n" +
	"\x11removed_tower_ids\x18\x02 \x03(\tR\x0fremovedTowerIds\"\xf6\x01\n" +
	"\x13SyncDamageBroadcast\x12\x19\n" +
	"\btower_id\x18\x01 \x01(\tR\atowerId\x12\x19\n" +
	"\benemy_id\x18\x02 \x01(\tR\aenemyId\x12\x16\n" +
	"\x06damage\x18\x03 \x01(\x05R\x06damage\x12\x17\n" +
	"\ais_crit\x18\x04 \x01(\bR\x06isCrit\x12\x17\n" +
	"\ais_kill\x18\x05 \x01(\bR\x06isKill\x12$\n" +
	"\bposition\x18\x06 \x01(\v2\b.Vector3R\bposition\x12\x1f\n" +
	"\vdamage_type\x18\a \x01(\x05R\n" +
	"damageType\x12\x18\n" +
	"\aeffects\x18\b \x03(\x05R\aeffects\"]\n" +
	"\x10EnemySpawnNotify\x12.\n" +
	"\x05enemy\x18\x01 \x01(\v2\x18.towerdefense.EnemyStateR\x05enemy\x12\x19\n" +
	"\bwave_num\x18\x02 \x01(\x05R\awaveNum\"\xd1\x01\n" +
	"\x10EnemyDeathNotify\x12\x19\n" +
	"\benemy_id\x18\x01 \x01(\tR\aenemyId\x12&\n" +
	"\x0fkiller_tower_id\x18\x02 \x01(\tR\rkillerTowerId\x12(\n" +
	"\x10killer_player_id\x18\x03 \x01(\tR\x0ekillerPlayerId\x12\x1f\n" +
	"\vreward_gold\x18\x04 \x01(\x05R\n" +
	"rewardGold\x12/\n" +
	"\x0edeath_position\x18\x05 \x01(\v2\b.Vector3R\rdeathPosition\"\xc6\x01\n" +
	"\x11TowerAttackNotify\x12\x19\n" +
	"\btower_id\x18\x01 \x01(\tR\atowerId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12-\n" +
	"\rfrom_position\x18\x03 \x01(\v2\b.Vector3R\ffromPosition\x12)\n" +
	"\vto_position\x18\x04 \x01(\v2\b.Vector3R\n" +
	"toPosition\x12\x1f\n" +
	"\vattack_type\x18\x05 \x01(\x05R\n" +
	"attackType\"\xd4\x01\n" +
	"\x0fPlayerStateSync\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x12\n" +
	"\x04gold\x18\x02 \x01(\x05R\x04gold\x12\x12\n" +
	"\x04life\x18\x03 \x01(\x05R\x04life\x12\x1d\n" +
	"\n" +
	"kill_count\x18\x04 \x01(\x05R\tkillCount\x12!\n" +
	"\ftotal_damage\x18\x05 \x01(\x03R\vtotalDamage\x12\x1f\n" +
	"\vtower_count\x18\x06 \x01(\x05R\n" +
	"towerCount\x12\x19\n" +
	"\bis_alive\x18\a \x01(\bR\aisAlive\"\xb0\x02\n" +
	"\x11GameStateSnapshot\x12\x19\n" +
	"\bwave_num\x18\x01 \x01(\x05R\awaveNum\x12\x1b\n" +
	"\tgame_time\x18\x02 \x01(\x02R\bgameTime\x122\n" +
	"\aenemies\x18\x03 \x03(\v2\x18.towerdefense.EnemyStateR\aenemies\x120\n" +
	"\x06towers\x18\x04 \x03(\v2\x18.towerdefense.TowerStateR\x06towers\x127\n" +
	"\aplayers\x18\x05 \x03(\v2\x1d.towerdefense.PlayerStateSyncR\aplayers\x12\x1f\n" +
	"\vgame_status\x18\x06 \x01(\tR\n" +
	"gameStatus\x12#\n" +
	"\rsnapshot_time\x18\a \x01(\x03R\fsnapshotTime\"\x19\n" +
	"\x17RequestGameStateRequest\"\x8b\x01\n" +
	"\x18RequestGameStateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12;\n" +
	"\bsnapshot\x18\x02 \x01(\v2\x1f.towerdefense.GameStateSnapshotR\bsnapshot\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x9b\x01\n" +
	"\tBuffState\x12\x17\n" +
	"\abuff_id\x18\x01 \x01(\x05R\x06buffId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x05R\bduration\x12\x1f\n" +
	"\vstack_count\x18\x04 \x01(\x05R\n" +
	"stackCount\x12\x1b\n" +
	"\tsource_id\x18\x05 \x01(\tR\bsourceId\"i\n" +
	"\x0eBuffSyncNotify\x12-\n" +
	"\x05buffs\x18\x01 \x03(\v2\x17.towerdefense.BuffStateR\x05buffs\x12(\n" +
	"\x10removed_buff_ids\x18\x02 \x03(\tR\x0eremovedBuffIdsB)Z\x12towerdefense/proto\xaa\x02\x12TowerDefense.Protob\x06proto3"

var (
	file_sync_proto_rawDescOnce sync.Once
	file_sync_proto_rawDescData []byte
)

func file_sync_proto_rawDescGZIP() []byte {
	file_sync_proto_rawDescOnce.Do(func() {
		file_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sync_proto_rawDesc), len(file_sync_proto_rawDesc)))
	})
	return file_sync_proto_rawDescData
}

var file_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_sync_proto_goTypes = []any{
	(*EnemyState)(nil),               // 0: towerdefense.EnemyState
	(*TowerState)(nil),               // 1: towerdefense.TowerState
	(*SyncStateBroadcast)(nil),       // 2: towerdefense.SyncStateBroadcast
	(*SyncEnemyBroadcast)(nil),       // 3: towerdefense.SyncEnemyBroadcast
	(*SyncTowerBroadcast)(nil),       // 4: towerdefense.SyncTowerBroadcast
	(*SyncDamageBroadcast)(nil),      // 5: towerdefense.SyncDamageBroadcast
	(*EnemySpawnNotify)(nil),         // 6: towerdefense.EnemySpawnNotify
	(*EnemyDeathNotify)(nil),         // 7: towerdefense.EnemyDeathNotify
	(*TowerAttackNotify)(nil),        // 8: towerdefense.TowerAttackNotify
	(*PlayerStateSync)(nil),          // 9: towerdefense.PlayerStateSync
	(*GameStateSnapshot)(nil),        // 10: towerdefense.GameStateSnapshot
	(*RequestGameStateRequest)(nil),  // 11: towerdefense.RequestGameStateRequest
	(*RequestGameStateResponse)(nil), // 12: towerdefense.RequestGameStateResponse
	(*BuffState)(nil),                // 13: towerdefense.BuffState
	(*BuffSyncNotify)(nil),           // 14: towerdefense.BuffSyncNotify
	(*Vector3)(nil),                  // 15: Vector3
}
var file_sync_proto_depIdxs = []int32{
	15, // 0: towerdefense.EnemyState.position:type_name -> Vector3
	15, // 1: towerdefense.TowerState.position:type_name -> Vector3
	0,  // 2: towerdefense.SyncStateBroadcast.enemies:type_name -> towerdefense.EnemyState
	1,  // 3: towerdefense.SyncStateBroadcast.towers:type_name -> towerdefense.TowerState
	0,  // 4: towerdefense.SyncEnemyBroadcast.enemies:type_name -> towerdefense.EnemyState
	1,  // 5: towerdefense.SyncTowerBroadcast.towers:type_name -> towerdefense.TowerState
	15, // 6: towerdefense.SyncDamageBroadcast.position:type_name -> Vector3
	0,  // 7: towerdefense.EnemySpawnNotify.enemy:type_name -> towerdefense.EnemyState
	15, // 8: towerdefense.EnemyDeathNotify.death_position:type_name -> Vector3
	15, // 9: towerdefense.TowerAttackNotify.from_position:type_name -> Vector3
	15, // 10: towerdefense.TowerAttackNotify.to_position:type_name -> Vector3
	0,  // 11: towerdefense.GameStateSnapshot.enemies:type_name -> towerdefense.EnemyState
	1,  // 12: towerdefense.GameStateSnapshot.towers:type_name -> towerdefense.TowerState
	9,  // 13: towerdefense.GameStateSnapshot.players:type_name -> towerdefense.PlayerStateSync
	10, // 14: towerdefense.RequestGameStateResponse.snapshot:type_name -> towerdefense.GameStateSnapshot
	13, // 15: towerdefense.BuffSyncNotify.buffs:type_name -> towerdefense.BuffState
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_sync_proto_init() }
func file_sync_proto_init() {
	if File_sync_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sync_proto_rawDesc), len(file_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sync_proto_goTypes,
		DependencyIndexes: file_sync_proto_depIdxs,
		MessageInfos:      file_sync_proto_msgTypes,
	}.Build()
	File_sync_proto = out.File
	file_sync_proto_goTypes = nil
	file_sync_proto_depIdxs = nil
}
